/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as DataRouteImport } from './routes/data'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutCriteriaRouteImport } from './routes/about.criteria'
import { Route as AboutFrameRouteImport } from './routes/about.frame'
import { Route as AboutGovernanceRouteImport } from './routes/about.governance'
import { Route as AboutMethodologyRouteImport } from './routes/about.methodology'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCriteriaRoute = AboutCriteriaRouteImport.update({
  id: '/about/criteria',
  path: '/about/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFrameRoute = AboutFrameRouteImport.update({
  id: '/about/frame',
  path: '/about/frame',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/about/governance',
  path: '/about/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMethodologyRoute = AboutMethodologyRouteImport.update({
  id: '/about/methodology',
  path: '/about/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/data': typeof DataRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/criteria': typeof AboutCriteriaRoute
  '/about/frame': typeof AboutFrameRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/artist/$id': typeof ArtistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/data': typeof DataRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/criteria': typeof AboutCriteriaRoute
  '/about/frame': typeof AboutFrameRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/artist/$id': typeof ArtistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/data': typeof DataRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/research': typeof ResearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/criteria': typeof AboutCriteriaRoute
  '/about/frame': typeof AboutFrameRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/artist/$id': typeof ArtistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/data'
    | '/privacy'
    | '/request'
    | '/research'
    | '/sitemap.xml'
    | '/about/criteria'
    | '/about/frame'
    | '/about/governance'
    | '/about/methodology'
    | '/artist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/data'
    | '/privacy'
    | '/request'
    | '/research'
    | '/sitemap.xml'
    | '/about/criteria'
    | '/about/frame'
    | '/about/governance'
    | '/about/methodology'
    | '/artist/$id'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/data'
    | '/privacy'
    | '/request'
    | '/research'
    | '/sitemap.xml'
    | '/about/criteria'
    | '/about/frame'
    | '/about/governance'
    | '/about/methodology'
    | '/artist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRoute
  DataRoute: typeof DataRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  ResearchRoute: typeof ResearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AboutCriteriaRoute: typeof AboutCriteriaRoute
  AboutFrameRoute: typeof AboutFrameRoute
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  AboutMethodologyRoute: typeof AboutMethodologyRoute
  ArtistIdRoute: typeof ArtistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/criteria': {
      id: '/about/criteria'
      path: '/about/criteria'
      fullPath: '/about/criteria'
      preLoaderRoute: typeof AboutCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/frame': {
      id: '/about/frame'
      path: '/about/frame'
      fullPath: '/about/frame'
      preLoaderRoute: typeof AboutFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/governance': {
      id: '/about/governance'
      path: '/about/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/methodology': {
      id: '/about/methodology'
      path: '/about/methodology'
      fullPath: '/about/methodology'
      preLoaderRoute: typeof AboutMethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRoute,
  DataRoute: DataRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  ResearchRoute: ResearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AboutCriteriaRoute: AboutCriteriaRoute,
  AboutFrameRoute: AboutFrameRoute,
  AboutGovernanceRoute: AboutGovernanceRoute,
  AboutMethodologyRoute: AboutMethodologyRoute,
  ArtistIdRoute: ArtistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
